title: news
description: >-
  <script async src="https://telegram.org/js/telegram-widget.js?14"
  data-telegram-post="QVids/389" data-width="100%"></script>
template:
  repo: news-template
  name: news
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
